# Generated by Django 4.2.1 on 2023-05-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('cronic_disease_1', models.CharField(max_length=50)),
                ('cronic_disease_2', models.CharField(max_length=50)),
                ('cronic_disease_3', models.CharField(max_length=50)),
                ('cronic_disease_4', models.CharField(max_length=50)),
                ('cronic_disease_5', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cluster_id', models.IntegerField()),
                ('if_transmit', models.BooleanField()),
                ('date_of_contamination', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('numberofUsers', models.IntegerField()),
                ('numberOfSickUsers', models.IntegerField()),
                ('centroidLatitude', models.FloatField()),
                ('centroidLongitude', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('radius', models.FloatField()),
                ('spreadRate', models.FloatField()),
                ('users', models.ManyToManyField(to='pfe_app.user')),
            ],
        ),
    ]
