# Generated by Django 4.2.1 on 2023-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0002_alter_user_clusterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cronic_disease_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cronic_disease_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cronic_disease_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cronic_disease_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cronic_disease_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_contamination',
            field=models.DateField(null=True),
        ),
    ]
