# Generated by Django 4.2.1 on 2023-05-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0003_alter_user_cronicdisease1_alter_user_cronicdisease2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='centroidLatitude',
            new_name='centroid_latitude',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='centroidLongitude',
            new_name='centroid_longitude',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='numberOfSickUsers',
            new_name='number_of_sick_users',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='numberofUsers',
            new_name='number_of_users',
        ),
        migrations.RenameField(
            model_name='cluster',
            old_name='spreadRate',
            new_name='spread_rate',
        ),
    ]
