# Generated by Django 4.2.1 on 2023-05-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0004_rename_centroidlatitude_cluster_centroid_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='users',
        ),
    ]
