# Generated by Django 4.2.1 on 2023-05-12 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0005_remove_cluster_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='spread_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2023, 5, 12))), name='no_future_date_of_birth'),
        ),
    ]
