# Generated by Django 4.2.1 on 2023-05-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0008_alter_user_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommandation',
            field=models.FloatField(null=True),
        ),
    ]
