# Generated by Django 4.2.1 on 2023-05-14 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0009_user_recommandation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='no_future_date_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2023, 5, 14))), name='no_future_date_of_birth'),
        ),
    ]
