# Generated by Django 4.2.1 on 2023-05-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0010_remove_user_no_future_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cluster_id',
            field=models.ForeignKey(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, to='pfe_app.cluster'),
        ),
    ]
