# Generated by Django 4.2.1 on 2023-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0011_alter_user_cluster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='if_transmit',
            field=models.BooleanField(null=True),
        ),
    ]
