# Generated by Django 4.2.1 on 2023-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_app', '0013_alter_user_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(null=True),
        ),
    ]
