name: projet_de_fin_d_etude
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  google_fonts: ^4.0.4
  latlng: ^0.2.1
  latlong2: ^0.8.1
  path: ^1.8.3
  sqflite: ^2.2.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
